# action.yml
name: 'haskell-stan'
author: "Kowainik — Veronika Romashkina, Dmitrii Kovanikov"
description: 'Haskell Static Analyser'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  stanPath:
    description: 'Path to Stan inside Docker container'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}

  pre-entrypoint: 'setup.sh'
  env:
    TEST_ENV: '1234'

branding:
  color: yellow
  icon: search
